export const MESSAGES_CONSTANTS = {
    NEW_MESSAGE: 1,
    DELETED_MESSAGE: 2,
    MESSAGES_QUANTITY: 25
};

export const DIALOG_CONSTANTS = {
    NEW_DIALOG: 1,
    DELETED_DIALOG: 2
};

export const FRIEND_CONSTANTS = {
    NEW_REQUEST: 1,
    CONFIRM: 2,
    DECLINE: 3
};